"""
Task 2: State Structure
=======================
Defines the shared state that flows through the entire LangGraph workflow.
Every node reads from and writes to this state object.
"""

from typing import TypedDict, Optional, List, Annotated
from langgraph.graph.message import add_messages


class CustomerSupportState(TypedDict):
    """
    Central state object for the Customer Support Automation System.

    Fields:
    -------
    customer_id     : Unique identifier for the customer (used for memory lookup)
    customer_name   : Customer's name (extracted from conversation or memory)
    query           : The raw customer query/message
    intent          : Classified intent - one of: Sales, Technical, Billing, Account, Memory
    department      : Department the query is routed to
    retrieved_context : Relevant text chunks retrieved from the RAG knowledge base
    conversation_history : List of past messages retrieved from SQLite memory
    requires_approval : True if the request needs human supervisor approval
    approval_status : 'pending', 'approved', or 'rejected'
    draft_response  : Initial response generated by the department agent
    supervisor_notes : Feedback or edits from the Supervisor agent
    final_response  : Polished final response sent to the customer
    error           : Any error message encountered during processing
    """

    # Customer identification
    customer_id: str
    customer_name: Optional[str]

    # Query details
    query: str
    intent: Optional[str]
    department: Optional[str]

    # RAG context
    retrieved_context: Optional[str]

    # Memory
    conversation_history: Optional[List[dict]]

    # Human-in-the-Loop approval
    requires_approval: bool
    approval_status: Optional[str]   # 'pending' | 'approved' | 'rejected'

    # Response pipeline
    draft_response: Optional[str]
    supervisor_notes: Optional[str]
    final_response: Optional[str]

    # Error handling
    error: Optional[str]
